baseURL = "https://vutheo.github.io/workshop/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "en"

# Change the default theme to be used when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme. Can be "red", "blue", "green", or custom variant.
  themeVariant = "workshop"

  # GitHub repository link for content
  editURL = "https://github.com/Vutheo/workshop/tree/main/content"

  description = ""
  author = "Vũ Thị Thanh Thảo"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]

[Languages.en]
title = "Internship Report"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> My GitHub Repo"
identifier = "My GitHub Repo"
url = "https://github.com/Vutheo/workshop"
weight = 21

[Languages.vi]
title = "Báo cáo thực tập"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub của tôi"
identifier = "GitHub cua toi"
url = "https://github.com/Vutheo/workshop"
weight = 21

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true